spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/big_event?serverTimezone=GMT%2B8
        username: root
        password: 15193651772Aa!
mybatis:
    configuration:
        map-underscore-to-camel-case: true # 开启驼峰命名和下划线命名的自动转换
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql